/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class frc_robot_subsystems_Lidar */

#ifndef _Included_frc_robot_subsystems_Lidar
#define _Included_frc_robot_subsystems_Lidar
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_frc_robot_subsystems_Lidar_construct
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_frc_robot_subsystems_Lidar_startMotor
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_frc_robot_subsystems_Lidar_startScan
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_frc_robot_subsystems_Lidar_poll
  (JNIEnv *, jobject, jobject);

JNIEXPORT void JNICALL Java_frc_robot_subsystems_Lidar_stopScan
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_frc_robot_subsystems_Lidar_stopMotor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
